# Generated by Django 6.0 on 2026-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('checklist', 'Checklist')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
